name: query-git-action
description: query the state of a git repo
author: romnn
branding:
  icon: info
  color: white
inputs:
  repo:
    description: path of the git repository to query
    required: false
outputs:
  git_commit:
    value: ${{ steps.query.outputs.GIT_COMMIT }}
  scm_status:
    value: ${{ steps.query.outputs.SCM_STATUS }}
  tree_state:
    value: ${{ steps.query.outputs.TREE_STATE }}
  scm_revision:
    value: ${{ steps.query.outputs.SCM_REVISION }}
  major_version:
    value: ${{ steps.query.outputs.MAJOR_VERSION }}
  minor_version:
    value: ${{ steps.query.outputs.MINOR_VERSION}}
  docker_tag:
    value: ${{ steps.query.outputs.DOCKER_TAG}}
  semver_version:
    value: ${{ steps.query.outputs.SEMVER_VERSION}}
  build_date:
    value: ${{ steps.query.outputs.BUILD_DATE}}
runs:
  using: node16
  main: dist/index.js
