name: test

on: ['push']

jobs:
  query:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: query the git repo
        id: query
        uses: ./
        
      - name: use the action's output variables
        run: |
          echo '${{ steps.query.outputs.stable_build_git_commit }}'
          echo '${{ steps.query.outputs.stable_build_scm_status }}'
          echo '${{ steps.query.outputs.stable_build_scm_revision }}'
          echo '${{ steps.query.outputs.stable_build_major_version }}'
          echo '${{ steps.query.outputs.stable_build_minor_version }}'
          echo '${{ steps.query.outputs.stable_docker_tag }}'
          echo '${{ steps.query.outputs.stable_semver_version }}'
          echo '${{ steps.query.outputs.stable_build_date }}'
          echo '${{ steps.query.outputs.stable_version }}'
          echo '${{ steps.query.outputs.git_commit }}'
          echo '${{ steps.query.outputs.git_tree_state }}'
          echo '${{ steps.query.outputs.git_version }}'
          echo '${{ steps.query.outputs.git_major }}'
          echo '${{ steps.query.outputs.git_minor }}'
          echo '${{ steps.query.outputs.build_date }}'

  query-in-container:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
    steps:
      - uses: actions/checkout@v2
      - name: query the git repo
        id: query
        uses: ./
        
      - name: use the action's output variables
        run: |
          echo '${{ steps.query.outputs.stable_build_git_commit }}'
          echo '${{ steps.query.outputs.stable_build_scm_status }}'
          echo '${{ steps.query.outputs.stable_build_scm_revision }}'
          echo '${{ steps.query.outputs.stable_build_major_version }}'
          echo '${{ steps.query.outputs.stable_build_minor_version }}'
          echo '${{ steps.query.outputs.stable_docker_tag }}'
          echo '${{ steps.query.outputs.stable_semver_version }}'
          echo '${{ steps.query.outputs.stable_build_date }}'
          echo '${{ steps.query.outputs.stable_version }}'
          echo '${{ steps.query.outputs.git_commit }}'
          echo '${{ steps.query.outputs.git_tree_state }}'
          echo '${{ steps.query.outputs.git_version }}'
          echo '${{ steps.query.outputs.git_major }}'
          echo '${{ steps.query.outputs.git_minor }}'
          echo '${{ steps.query.outputs.build_date }}'
