name: test

on: [push]

jobs:
  query:
    runs-on: ${{ matrix.os }}
    name: query on ${{ matrix.os }}
    strategy: 
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: query the git repo
        id: query
        uses: ./
        
      - name: show output variables
        run: |
          echo "${{ steps.query.outputs.git_commit }}"
          echo "${{ steps.query.outputs.scm_status }}"
          echo "${{ steps.query.outputs.tree_state }}"
          echo "${{ steps.query.outputs.scm_revision }}"
          echo "${{ steps.query.outputs.major_version }}"
          echo "${{ steps.query.outputs.minor_version }}"
          echo "${{ steps.query.outputs.docker_tag }}"
          echo "${{ steps.query.outputs.semver_version }}"
          echo "${{ steps.query.outputs.build_date }}"

  query-custom-location:
    runs-on: ${{ matrix.os }}
    name: query custom location on ${{ matrix.os }}
    strategy: 
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: clone repo into custom location
        run: >
          git clone
          https://github.com/romnn/film-borders.git
          ./some/git/repo

      - name: query the git repo
        id: query
        uses: ./
        with:
          repo: ./some/git/repo
        
      - name: show output variables
        run: |
          echo "${{ steps.query.outputs.git_commit }}"
          echo "${{ steps.query.outputs.scm_status }}"
          echo "${{ steps.query.outputs.tree_state }}"
          echo "${{ steps.query.outputs.scm_revision }}"
          echo "${{ steps.query.outputs.major_version }}"
          echo "${{ steps.query.outputs.minor_version }}"
          echo "${{ steps.query.outputs.docker_tag }}"
          echo "${{ steps.query.outputs.semver_version }}"
          echo "${{ steps.query.outputs.build_date }}"
