name: test

on: [push]

jobs:
  query:
    runs-on: ${{ matrix.os }}
    name: query on ${{ matrix.os }}
    strategy: 
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: query the git repo
        id: query
        uses: ./
        
      - name: show output variables
        run: |
          echo "${{ steps.query.outputs.git_commit }}"
          echo "${{ steps.query.outputs.scm_status }}"
          echo "${{ steps.query.outputs.tree_state }}"
          echo "${{ steps.query.outputs.scm_revision }}"
          echo "${{ steps.query.outputs.major_version }}"
          echo "${{ steps.query.outputs.minor_version }}"
          echo "${{ steps.query.outputs.docker_tag }}"
          echo "${{ steps.query.outputs.semver_version }}"
          echo "${{ steps.query.outputs.build_date }}"

  query-custom-location:
    runs-on: ${{ matrix.os }}
    name: query custom location on ${{ matrix.os }}
    strategy: 
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: set env variables
        run: |
          echo "REPO_DEST=$HOME/some/git/repo" >> "$GITHUB_ENV"
          echo "REPO_URL=https://github.com/romnn/film-borders.git" >> "$GITHUB_ENV"

      - name: clone repo into custom location
        run: |
          # mkdir -p "${{ env.REPO_DEST }}"
          git clone "${{ env.REPO_URL }}" "${{ env.REPO_DEST }}"

      - name: query the git repo
        id: query
        uses: ./
        with:
          repo: "${{ env.REPO_DEST }}"
        
      - name: show output variables
        run: |
          echo "${{ steps.query.outputs.git_commit }}"
          echo "${{ steps.query.outputs.scm_status }}"
          echo "${{ steps.query.outputs.tree_state }}"
          echo "${{ steps.query.outputs.scm_revision }}"
          echo "${{ steps.query.outputs.major_version }}"
          echo "${{ steps.query.outputs.minor_version }}"
          echo "${{ steps.query.outputs.docker_tag }}"
          echo "${{ steps.query.outputs.semver_version }}"
          echo "${{ steps.query.outputs.build_date }}"
